### ISSUE TITLE
strollut_fbmap_hweight_129 error on ARM 32bit

### ISSUE THREAD

**Issue by Geneo-5** [grgbr/stroll#1]
https://github.com/grgbr/stroll/blob/02ea33117b048971e1cda855f67c6d8147d98556/test/fbmap.c#L362

diff --git a/test/fbmap.c b/test/fbmap.c
index efc64ec..866df92 100644
--- a/test/fbmap.c
+++ b/test/fbmap.c
@@ -359,6 +359,7 @@ CUTE_TEST(strollut_fbmap_hweight_65)
        cute_check_uint(stroll_fbmap_hweight(&strollut_fbmap_65), equal, 12U);
 }
 
+#if __WORDSIZE == 64
 CUTE_TEST(strollut_fbmap_hweight_129)
 {
        cute_check_uint(stroll_fbmap_hweight(&strollut_fbmap_null_129),
@@ -366,6 +367,9 @@ CUTE_TEST(strollut_fbmap_hweight_129)
                        0);
        cute_check_uint(stroll_fbmap_hweight(&strollut_fbmap_129), equal, 23U);
 }
+#else  /* __WORDSIZE != 64 */
+STROLLUT_FBMAP_NO64BITS(strollut_fbmap_hweight_129)
+#endif /* __WORDSIZE == 64 */
 
 #if defined(CONFIG_STROLL_ASSERT_API)
 CUTE_TEST(strollut_fbmap_test_all_assert)

**Comment by grgbr** [comment]
Fixed in e97d67.
